# Site metadata
title: edpe.nz
description: Profile and portfolio of Edward Peek

url: "https://edpe.nz"
baseurl: ""

email: edwardpeek@gmail.com

# Build config
markdown: kramdown

collections:
  software:
    output: true
    permalink: /software/:path

  academia:
    output: true
    permalink: /academia/:path
